### ISSUE TITLE
Uses native ECDH implementation

### ISSUE THREAD

**Issue by wanderer** [ethereumjs/node-devp2p-dpt#6]
Pending on this https://github.com/bitcoin/secp256k1/issues/352

**Comment by fanatid** [comment]
Where ECDH used in discover peer protocol? Or this package should support encryption and frames? (https://github.com/ethereum/devp2p/blob/master/rlpx.md)

**Comment by wanderer** [comment]
you are correct @fanatid this is an invalid issue
